version: '3'

services:

  db:
    container_name: db
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - ./database_dumps:/app/database_dumps

  web:
    container_name: web
    platform: linux/amd64
    build: .
    volumes:
      - ./:/app
      - ./bash/bashrc.sh:/root/.bashrc
    depends_on:
      - db
    ports:
      - 8000:8000
    command: sh bash/run-dev.sh
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres

  cli:
    container_name: cli
    platform: linux/amd64
    build: platformsh-cli
    volumes:
      - ./media:/app/media
      - ./database_dumps:/app/database_dumps
    env_file:
      - .env
