services:
  db:
    image: postgres:12.0
    ports:
      - 5432:5432

  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-django-root
        IMAGE_TAG: preview
    volumes:
      - ./:/app
      - media:/media
    depends_on:
      - db
      - redis
    command: poetry run python /app/manage.py runserver 0.0.0.0:8080
    ports:
      - 8000:8080
    env_file:
      - .env
    environment:
      - ENVIRONMENT=develop
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - SECRET_KEY=abc123
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@tna.dev
      - FEATURE_BETA_BANNER_ENABLED=False
      - KONG_CLIENT_VERIFY_CERTIFICATES=False
      - KEEP_ALIVE=30
      - WAGTAILAPI_BASE_URL=http://host.docker.internal:8000
      - REDIS_URL=redis://:redis@redis:6379

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 8001:8000

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:preview
    environment:
      - PLATFORMSH_CLI_TOKEN=${PLATFORMSH_CLI_TOKEN}
      - PLATFORM_PROJECT_ID=rasrzs7pi6sd4
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
    volumes:
      - ./:/app
      - ./dev:/home/app/.local/bin/tasks:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - media:/media

  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass redis"
    ports:
      - 6379:6379

volumes:
  media:
