version: '3'

services:
  db:
    image: postgres:12.0
    expose:
      - 5432
    volumes:
     - ./database_dumps:/app/database_dumps
  web:
    platform: linux/amd64
    build: .
    volumes:
      - ./:/app
    depends_on:
     - db
    ports:
     - 8000:8000 # runserver
     - 8001:8001 # mkdocs serve
    # Closely match prod server
    # command: pipenv run gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 3600 --workers 3 --reload --capture-output
    # Server for better debugging output
    command: tail -f /dev/null  # do nothing forever. Use fab sh to run the django server
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
  cli:
    platform: linux/amd64
    build: platformsh-cli
    volumes:
      - ./media:/app/media
      - ./database_dumps:/app/database_dumps
    env_file:
      - .env
