version: '3'

services:

  db:
    container_name: db
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - ./database_dumps:/app/database_dumps

  web:
    container_name: web
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/nationalarchives/tna-python-django-root
        BASE_IMAGE_TAG: rooted-images
    volumes:
      - ./etna:/app/etna
      - ./config:/app/config
      - ./sass:/app/sass
      - ./scripts:/app/scripts
      - ./static:/app/static
      - ./templates:/app/templates
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./dev/bin:/home/app/.local/bin/dev
      - ./dev/run.sh:/app/run.sh
      - media:/media
    depends_on:
      - db
    ports:
      - 8000:8080
    command: sh /app/run.sh
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - ENVIRONMENT=develop
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@tna-development.example
      - KEEP_ALIVE=30

  cli:
    container_name: cli
    platform: linux/amd64
    build: platformsh-cli
    volumes:
      - media:/app/media
      - ./database_dumps:/app/database_dumps
    env_file:
      - .env

  docs:
    container_name: docs
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 8001:8000

volumes:
  media:
