version: '3'

services:

  db:
    container_name: db
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - ./database_dumps:/app/database_dumps

  web:
    container_name: web
    build:
      context: .
      args:
        BASE_IMAGE: ghcr.io/nationalarchives/tna-python-django-root
        BASE_IMAGE_TAG: rooted-images # TODO: Change to latest on merge Docker to main
    volumes:
      - .:/app
      - ./dev/bin/build:/home/app/.local/bin/build
      - ./dev/bin/build-css:/home/app/.local/bin/build-css
      - ./dev/bin/build-js:/home/app/.local/bin/build-js
      - ./dev/bin/createsuperuser:/home/app/.local/bin/createsuperuser
      - ./dev/bin/dev:/home/app/.local/bin/dev
      - ./dev/bin/dev-css:/home/app/.local/bin/dev-css
      - ./dev/bin/dev-js:/home/app/.local/bin/dev-js
      - ./dev/bin/format:/home/app/.local/bin/format
      - ./dev/bin/help:/home/app/.local/bin/help
      - ./dev/bin/makemigrations:/home/app/.local/bin/makemigrations
      - ./dev/bin/manage:/home/app/.local/bin/manage
      - ./dev/bin/pull-preview:/home/app/.local/bin/pull-preview
      - ./dev/bin/setup-npm:/home/app/.local/bin/setup-npm
      - ./dev/bin/tests:/home/app/.local/bin/tests
      - ./dev/bin/update-npm:/home/app/.local/bin/update-npm
      - ./dev/bin/update-poetry:/home/app/.local/bin/update-poetry
      - ./dev/bin/welcome:/home/app/.local/bin/welcome
      - media:/media
    depends_on:
      - db
    ports:
      - 8000:8080
    command: sh /app/dev/run.sh
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - ENVIRONMENT=develop
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@tna-development.example
      - FEATURE_BETA_BANNER_ENABLED=False
      - KEEP_ALIVE=30

  cli:
    container_name: cli
    platform: linux/amd64
    build: platformsh-cli
    volumes:
      - media:/app/media
      - ./database_dumps:/app/database_dumps
    env_file:
      - .env

  docs:
    container_name: docs
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 8001:8000

volumes:
  media:
