site_name: Etna
repo_url: https://github.com/nationalarchives/ds-wagtail
dev_addr: 0.0.0.0:8001
theme:
  name: material
  font: false
markdown_extensions:
  - admonition
  - sane_lists
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 'Home': 'index.md'
  - 'Developer guide':
      - 'Project conventions': 'developer-guide/project-conventions.md'
      - 'Backend development': 'developer-guide/backend.md'
      - 'Frontend development': 'developer-guide/frontend.md'
      - 'Fetching production data': 'developer-guide/fetching-production-data.md'
      - 'Working with VS Code': 'developer-guide/vscode.md'
  - 'Environments and infrastructure':
      - 'Hosted environments': 'infra/environments.md'
      - 'Infrastructure overview': 'infra/infrastructure.md'
      - 'Scheduled tasks': 'infra/scheduled-tasks.md'
      - 'Configuring an environment': 'infra/configuring-an-environment.md'
      - 'Testing an environment': 'infra/testing-an-environment.md'
      - 'Caching strategy': 'infra/caching-strategy.md'
  - 'Unique features':
      - 'Search and record data': 'features/search-and-record-data.md'
