[tool.poetry]
name = "Etna"
version = "0.1.0"
description = ""
authors = ["Dan Bentley <dan@numiko.com>"]

[tool.poetry.dependencies]
python = "^3.8"
gunicorn = "^20.1.0"
elasticsearch = "^7.12.0"
wagtail = "^2.12.3"
platformshconfig = "^2.4.0"
pyquery = "^1.4.3"
wagtail-generic-chooser = "^0.2.1"
psycopg2 = "^2.9.1"
wagtailfontawesome = "^1.2.1"
wagtailmedia = "^0.7.1"
django-allauth = "^0.45.0"
python-magic = "^0.4.24"
django-redis = "^5.0.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
ipdb = "^0.13.7"
django-extensions = "^3.1.2"
responses = "^0.13.3"
coverage = "^5.5"
ddt = "^1.4.2"
flake8 = "^4.0.1"
isort = "^5.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
