[tool.poetry]
name = "Etna"
description = ""
version = "0.0.0"
authors = ["James Biggs <james.biggs@nationalarchives.gov.uk>"]

[tool.poetry.dependencies]
python = "~3.11"
gunicorn = "~21.2"
Django = "~4.2"
wagtail = "~5.1"
django-taggit = "~4.0"
platformshconfig = "~2.4"
pyquery = "~2.0"
wagtail-generic-chooser = "~0.6"
psycopg2 = "~2.9"
wagtailmedia = "~0.14"
django-allauth = "~0.54"
python-magic = "~0.4"
django-redis = "~5.3"
wagtail-font-awesome-svg = "~0.0"
django-birdbath = "~1.1"
bleach = "~6.0"
sentry-sdk = "~1.29"
wagtail-metadata = "~4.0"

[tool.poetry.dev-dependencies]
black = "~23.7"
ipdb = "~0.13"
django-extensions = "~3.2"
responses = "~0.23"
coverage = "~7.2"
flake8 = "~6.1"
isort = "~5.12"
pymdown-extensions = "~10.1"
mkdocs-material = "~9.1"
django-debug-toolbar = "~4.1"
wagtail-factories = "~4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line_length = 88
target-version = ['py39']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.venv
    | __pycache__
    | _build
    | build
    | docs
    | venv
    | node_modules
  )/
)
'''
