[tool.poetry]
name = "Etna"
version = "23.09.19.13"
description = ""
authors = ["James Biggs <james.biggs@nationalarchives.gov.uk>"]

[tool.poetry.dependencies]
bleach = "~6.0"
Django = "~4.2"
django-allauth = "~0.55"
django-birdbath = "~1.1"
django-redis = "~5.3"
django-taggit = "~4.0"
gunicorn = "~21.2"
platformshconfig = "~2.4"
psycopg2-binary = "~2.9"
pyquery = "~2.0"
python = "~3.11"
python-magic = "~0.4"
sentry-sdk = "~1.30"
wagtail = "~5.1"
wagtail-font-awesome-svg = "~0.0"
wagtail-generic-chooser = "~0.6"
wagtailmedia = "~0.14"
wagtail-metadata = "~4.0"

[tool.poetry.dev-dependencies]
black = "~23.7"
coverage = "~7.3"
django-debug-toolbar = "~4.2"
django-extensions = "~3.2"
flake8 = "~6.1"
ipdb = "~0.13"
isort = "~5.12"
mkdocs-material = "~9.2"
pymdown-extensions = "~10.3"
responses = "~0.23"
wagtail-factories = "~4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line_length = 88
target-version = ['py39']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.venv
    | __pycache__
    | _build
    | build
    | docs
    | venv
    | node_modules
  )/
)
'''
