[tool.poetry]
name = "Etna"
version = "0.1.0"
description = ""
authors = ["Dan Bentley <dan@numiko.com>"]

[tool.poetry.dependencies]
python = "^3.8"
gunicorn = "^20.1.0"
Django = "~4.1"
wagtail = "~5.0"
django-taggit = "~3.1"
platformshconfig = "^2.4.0"
pyquery = "^2.0.0"
wagtail-generic-chooser = "~0.5.1"
psycopg2 = "^2.9.1"
wagtailmedia = "~0.14"
django-allauth = "~0.54"
python-magic = "^0.4.24"
django-redis = "^5.0.0"
wagtail-font-awesome-svg = "0.0.3"
django-birdbath = "~1.1.0"
bleach = "^6.0.0"
sentry-sdk = "~1.23"
wagtail-metadata = "~4.0.2"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
ipdb = "^0.13.7"
django-extensions = "^3.1.2"
responses = "^0.23.1"
coverage = "^7.2"
flake8 = "~5.0"
isort = "^5.12.0"
pymdown-extensions = "^9.11"
mkdocs-material = "~9.1"
django-debug-toolbar = "~4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line_length = 88
target-version = ['py39']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.venv
    | __pycache__
    | _build
    | build
    | docs
    | venv
    | node_modules
  )/
)
'''
