# Generated by Django 4.2.7 on 2023-11-22 15:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("whatson", "0005_alter_eventpage_venue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsession",
            name="event_id",
            field=models.CharField(
                blank=True, editable=False, null=True, verbose_name="event ID"
            ),
        ),
        migrations.AddField(
            model_name="eventsession",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="eventsession",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="whatson.eventpage",
            ),
        ),
    ]
