# Generated by Django 5.0.6 on 2024-06-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_authorindexpage_authorpage_authortag_delete_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorpage",
            options={
                "verbose_name": "Person page",
                "verbose_name_plural": "Person pages",
            },
        ),
        migrations.RenameField(
            model_name="authorpage",
            old_name="summary",
            new_name="author_summary",
        ),
    ]
