# Generated by Django 5.0.6 on 2024-06-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0003_alter_authorpage_options_and_more"),
        ("images", "0008_alter_customimagerendition_file"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuthorPage",
            new_name="PersonPage",
        ),
    ]
