# Generated by Django 5.0.6 on 2024-06-25 10:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0004_rename_authorpage_personpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="research_summary",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
