name: Get version tag

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Get tag from branch, tag or release
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
