name: Build Docker image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      latest:
        required: false
        type: boolean
        default: false
        
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignore: DL3007
      - name: Build and push image
        run: |
          IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/${{ vars.DOCKER_IMAGE_NAME }}" | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> "$GITHUB_OUTPUT"
          docker build --tag $IMAGE_ID:${{ inputs.version }} --platform=linux/amd64 .
          docker push $IMAGE_ID:${{ inputs.version }}
      - name: Tag latest
        if: inputs.latest
        run: |
          docker tag $IMAGE_ID:${{ inputs.version }} $IMAGE_ID:latest --platform=linux/amd64 .
          docker push $IMAGE_ID:latest
