name: Generate calver

on:
  workflow_call:
  
jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate calver
        run: echo "CALVER=$(date +%Y-%m-%d)-$GITHUB_RUN_NUMBER" >> "$GITHUB_OUTPUT"
