name: Docker build and deploy

on:
  push:
    branches:
      - main
      - develop # TODO: Remove once moving to trunk-based
      - feature/*

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate tag
        id: version-tag
        uses: ./.github/workflows/_get-version-tag.yml
      - name: Build
        uses: ./.github/workflows/_docker-build.yml
        with:
          version: ${{ steps.version-tag.outputs.VERSION }}
      - name: Install AWS CLI
        uses: ./.github/workflows/_install-aws.yml
      - name: Deploy to AWS
        run: aws ssm put-parameter --name "/devops/private-beta/version" --type "String" --value "${{ steps.version-tag.outputs.VERSION }}" --overwrite
      # TODO: If feature branch, deploy new environment
