name: CI

on:
  pull_request:

jobs:
  ci:
    name: Tests
    uses: ./.github/actions/tests
    with:
      python-version: ${{ vars.CI_PYTHON_VERSION }}
      poetry-version: ${{ vars.CI_POETRY_VERSION }}
