name: CI

on:
  push:

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.5.1"

jobs:
  ci:
    name: Tests
    uses: ./.github/workflows/_tests.yml
    with:
      python-version: ${{ PYTHON_VERSION }}
      poetry-version: ${{ POETRY_VERSION }}
