name: Create release tag

on:
  push:
    branches:
      - 'release/[0-9]+.[0-9]+'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          VERSION=$(echo $BRANCH | sed -e 's/^release\///')
          COMMITS=$(git rev-list --count $BRANCH)
          TAG=$VERSION.$COMMITS
          git tag v$TAG
          git push origin --tags
