name: Create a release

on:
  workflow_dispatch:

jobs:
  build:
    name: Create a release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate tag
        id: version-tag
        uses: ./.github/workflows/_generate-calver-tag.yml
      - name: Create tag
        run: |
          TAG=v${{ steps.version-tag.outputs.CALVER }}
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Check out a new branch
        if: !inputs.base-tag
        run: git checkout -b release/$TAG
      - name: Push tag and branch
        run: |
          git tag $TAG
          git push origin --tags
          git push --set-upstream origin release/$TAG
