name: Create a release

on: workflow_dispatch
  
jobs:
  build:
    name: Create a release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate tag
        id: version-tag
        uses: ./.github/workflows/_generate-calver-tag.yml
      - name: Tag version
        run: |
          TAG=v${{ steps.version-tag.outputs.CALVER }}
          git tag $TAG
          git push origin --tags
