name: Docker

on:
  schedule:
    - cron: '44 6 * * *'
  push:
    branches:
      # - main
      # - develop
      - chore/docker-static-assets # TEMP

jobs:
  lint:
    runs-on: hadolint/hadolint:latest-debian
    steps:
      - name: Lint Dockerfile
        run: hadolint Dockerfile || true
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug
        run: ls -alh && pwd
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ github.event.repository.name }}-${{ github.ref_name }}:latest
