name: CI

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      python_version: 3.11
      poetry_version: 1.5.1
