name: CI

on:
  push:
    branches:
      - main
      - "release/**"

  pull_request:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install flake8
        run: python -m pip install flake8
      - name: flake8
        run: flake8 .
      - name: Install isort
        run: python -m pip install isort
      - name: Run isort
        run: isort -c .
      - name: Install Black
        run: python -m pip install black==22.1.0
      - name: Check compliance with Black
        run: black etna config --check --fast

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: cp .env.example .env
      - name: Start containers
        run: docker-compose up -d
      - name: Run tests
        run: |
          docker-compose exec -T web poetry run ./manage.py test
      - name: Check for missing migrations
        run: |
          docker-compose exec -T web poetry run ./manage.py makemigrations --check

  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm modules
        run: npm install
      - name: Run jest tests
        run: npm test
