name: CD (platform.sh)

on:
  release:
    types:
      - published

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/_tests.yml
    with:
      python-version: ${{ vars.CI_PYTHON_VERSION }}
      poetry-version: ${{ vars.CI_POETRY_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_CLI_TOKEN }}
          ssh-private-key: ${{ secrets.PLATFORM_SSH_KEY }}
          force-push: true
          environment-name: main

  notify-slack:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v4
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "A deployment to main is complete"
