name: CD (platform.sh)

on:
  push:
    branches:
      - main
      - develop
    paths:
      # Host config
      - '.plaform/**'
      - '.platform.app.yaml'
      - 'gunicorn.conf.py'
      # Python config
      - 'poetry.lock'
      - 'pyproject.toml'
      # NPM config
      - 'package.json'
      - 'package-lock.json'
      - 'webpack.config.js'
      # App changes
      - 'config/**'
      - 'sass/**'
      - 'scripts/**'
      - 'templates/**'
      - 'etna/**'

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.5.1"

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/_tests.yml
    with:
      python_version: ${{ env.PYTHON_VERSION }}
      poetry_version: ${{ env.POETRY_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_CLI_TOKEN }}
          ssh-private-key: ${{ secrets.PLATFORM_SSH_KEY }}
          force-push: true

  notify-slack:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v3
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "A deployment to ${{ github.head_ref || github.ref_name }} is complete"
