name: Release to staging

on:
  release:
    types:
      - published
  
jobs:
  build:
    name: Build Docker
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: ds-wagtail
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install AWS CLI
        uses: ./.github/workflows/install-aws.yml
      - name: Get tag
        id: version-tag
        uses: ./.github/workflows/version-tag.yml
      - name: Update application version on staging
        run: aws ssm put-parameter --name "/aj/test-value-deploy-version-staging" --type "String" --value "${{ steps.version-tag.outputs.VERSION }}" --overwrite
