name: Release to staging

on:
  workflow_call:
  # release:
  #   types:
  #     - published

jobs:
  build:
    name: Build and deploy to AWS
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        id: version-tag
        uses: ./.github/actions/get-version-tag
      - name: Build
        uses: ./.github/actions/docker-build
        with:
          version: ${{ steps.version-tag.outputs.version-tag }} # (23.09.24.1)
          latest: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}
      - name: Install AWS CLI
        uses: ./.github/actions/install-aws
      - name: Deploy to AWS
        run: aws ssm put-parameter --profile staging --name "/devops/private-beta/version" --type "String" --value "${{ steps.version-tag.outputs.VERSION }}" --overwrite
