name: Code coverage

on:
  push:
    branches: 
      - develop

jobs:
  code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON_VERSION
          fail_ci_if_error: true
          move_coverage_to_trash: true